#!/bin/bash

# NOT FINISHED. REF ONLY.

# Default
oc get quota -A -o json | jq -r '["namespace","daemonsets","deployments","pods","limits.cpu","limits.memory"], ["--------------------------","-----------","-----------","-----------","-----------","-----------"], (.items[] | [.metadata.namespace, (if (.status.hard | has("count/daemonsets.apps")) then (.status.hard."count/daemonsets.apps" + "/" + .status.used."count/daemonsets.apps") else "NA" end), (if (.status.hard | has("count/deployments.apps")) then (.status.hard."count/deployments.apps" + "/" + .status.used."count/deployments.apps") else "NA" end), (if (.status.hard | has("pods")) then (.status.hard.pods + "/" + .status.used.pods) else "NA" end), (if (.status.hard | has("limits.cpu")) then (.status.hard."limits.cpu" + "/" + .status.used."limits.cpu") else "NA" end), (if (.status.hard | has("limits.memory")) then (.status.hard."limits.memory" + "/" + .status.used."limits.memory") else "NA" end) ]) | @tsv' | column -t

# Extended
oc get quota -A -o json | jq -r '["namespace","configmaps","pvcs","pods","rcs","secrets","services","services.lb"], ["--------------------------","-----------","-----------","-----------","-----------","-----------","-----------","-----------"], (.items[] | [.metadata.namespace, (if (.status.hard | has("configmaps")) then (.status.hard.configmaps + "/" + .status.used.configmaps) else "NA" end), (if (.status.hard | has("persistentvolumeclaims")) then (.status.hard.persistentvolumeclaims + "/" + .status.used.persistentvolumeclaims) else "NA" end), (if (.status.hard | has("pods")) then (.status.hard.pods + "/" + .status.used.pods) else "NA" end), (if (.status.hard | has("replicationcontrollers")) then (.status.hard.replicationcontrollers + "/" + .status.used.replicationcontrollers) else "NA" end), (if (.status.hard | has("secrets")) then (.status.hard.secrets + "/" + .status.used.secrets) else "NA" end), (if (.status.hard | has("services")) then (.status.hard.services + "/" + .status.used.services) else "NA" end), (if (.status.hard | has("services.loadbalancers")) then (.status.hard."services.loadbalancers" + "/" + .status.used."services.loadbalancers") else "NA" end) ]) | @tsv' | column -t
